# Introduction to Numpy

## Import statement

Consider a **module** to be the same as a code library.

A file containing a set of functions you want to include in your application.

We can use the pre-determined or created module by using **import** keyword.

In [ ]:
# We are trying to use functions in 'numpy' module and call the module as 'np'.
import numpy as np

## What is numpy?

NumPy is a Python library used for working with **arrays**.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

 The array object in NumPy is called **ndarray**.

In [ ]:
# We can create a NumPy ndarray object by using the array() function.

temp = [1, 2, 3, 4]

print(np.array(temp))

[1 2 3 4]


## More functions in numpy

**arange()** function returns an array with evenly spaced elements as per the interval.

In [ ]:
# Creating an array from 1 to 9
print(np.arange(1, 10))

# Creating an array that contains numbers up until 14
print(np.arange(15))

# Crating an array that contains numbers from 2 to 21, but numbers increase by 2
print(np.arange(2, 22, 2))

[1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14 16 18 20]


The **linspace()** function returns number spaces evenly w.r.t interval.

Similar to numpy.arange() function but instead of step it uses sample number.

In [ ]:
# You have start as 1, end as 4, and you have 4 numbers in between with equal intervals
print(np.linspace(1, 4, num = 4))

print(np.linspace(2, 3, num = 5))

print(np.linspace(0, 100, num = 11))

[1. 2. 3. 4.]
[2.   2.25 2.5  2.75 3.  ]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


The **empty()** function returns a new array of given shape and type, with random values.

In [ ]:
a = np.empty(10)
print(a)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


The **full()** function returns a new array with the same shape and type as a given array filled with a fill_value.



In [ ]:
# dtype determines the type of values in the array
print(np.full(10, 4, dtype = float))

# np.inf is a floating point representation of (positive) infinity
print(np.full((2, 2), np.inf))

print(np.full((2, 2), [1, 2]))

[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
[[inf inf]
 [inf inf]]
[[1 2]
 [1 2]]


## Little more on using numpy...

In [ ]:
# 2D array...?
temp_matrix = np.array([[1,2,3,4], [5,6,7,8]])

In [ ]:
# Number of elements in array
print(temp_matrix.size)

# Dimension of array
print(temp_matrix.ndim)

# Shape of array
print(temp_matrix.shape)

8
2
(2, 4)


In [ ]:
# Changing the shape of the array
print(temp_matrix.reshape(1, 8))

# The transpose of a matrix is an operator which flips a matrix over its diagonal
print(temp_matrix.T)

[[1 2 3 4 5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[2,2,2],[3,3,3]])

# Multiplying by coordinates.
print(a * b.T)

# Returns the matrix product of two arrays.
print(np.matmul(a, b))

[[ 2  6]
 [ 6 12]
 [10 18]]
[[ 8  8  8]
 [18 18 18]
 [28 28 28]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

# Making two arrays into a single array
print(np.concatenate((arr1, arr2)))

# Used to stack the sequence of input arrays horizontally
print(np.hstack((arr1, arr2)))

# Used to stack the sequence of input arrays vertically
print(np.vstack((arr1, arr2)))

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Returns maximum value of the array
print(a.max())

# Returns minimum value of the array
print(a.min())

# Returns the sum of values of the array
print(a.sum())
print(a/si)
# Returns a copy of the array collapsed into one dimension
print(a.flatten())

b = np.array([0, 3, 2, 0, 2, 5, 1, 2])

# Returns the sorted unique elements of an array.
print(np.unique(b))

# Reverse the order of elements in an array along the given axis.
# The shape of the array is preserved, but the elements are reordered.
print(np.flip(a))

6
1
21
[1 2 3 4 5 6]
[0 1 2 3 5]
[[6 5]
 [4 3]
 [2 1]]


## Challenges

Extract all odd numbers from arr

In [ ]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(arr[arr % 2 !=0])

result = []
for i in arr:
  if i % 2 != 0:
    result.append(i)
print(result)

[1 3 5 7 9]
[1, 3, 5, 7, 9]


Convert a 1D array to a 2D array with 2 rows

In [ ]:
arr = np.arange(10)
arr = np.vstack((arr, arr))
arr

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

Compute the counts of row in the array below

In [ ]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))

In [ ]:
print(arr.shape[0])

row, col = arr.shape

6
